name: DISA-STIG-Remediation
on: workflow_dispatch

permissions:
  id-token: write
  contents: read
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!" 
