name: DISA-STIG-Remediation-DEV

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
  
jobs:
  my-job:
    runs-on: [VLABR1]
    steps:
      - name: my-step
        run: echo "Hello World!" 

  run-powershell:
    runs-on: [VLABR1]
    defaults:
      run:
        shell: powershell # use PowerShell 7; switch to 'powershell' for Windows PowerShell 5.1
        
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Show versions
        run: |
          $PSVersionTable
          whoami
          [Environment]::Is64BitProcess

      - name: Copy script to TEMP
        run: |
          $source = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath ".github\scripts\STIG-ID-WN10-ALL.ps1"
          $dest = Join-Path -Path $env:TEMP -ChildPath "STIG-ID-WN10-ALL.ps1"
          
          if (-not (Test-Path $source)) {
            throw "Script not found at $source"
          }
          
          Copy-Item $source $dest -Force
          Write-Host "Copied script to $dest"
