name: DISA-STIG-Remediation-DEV

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
  
jobs:
  my-job:
    runs-on: [VLABR1]
    steps:
      - name: my-step
        run: echo "Hello World!" 

  run-powershell:
    runs-on: [VLABR1]
    defaults:
      run:
        shell: powershell # use PowerShell 7; switch to 'powershell' for Windows PowerShell 5.1
        
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Copy script to machine
        run: |
          $repoRoot = $env:GITHUB_WORKSPACE
          $source = Join-Path -Path $repoRoot -ChildPath ".github\scripts\STIG-ID-WN10-ALL.ps1"
          $destFolder = "C:\stig-rem"
          $dest = Join-Path -Path $destFolder -ChildPath "STIG-ID-WN10-ALL.ps1"
                  
          if (-not (Test-Path $source)) {
            throw "Script not found at $source"            
          }

          # Validate destination exists
          if (-not (Test-Path $dest)) {
              New-Item -Path $destFolder -ItemType Directory -Force | Out-Null
          }
          
          Copy-Item -Path $source -Destination $dest -Force
          Write-Host "Copied script to $dest"
